server:
  port: 8099
  servlet:
    contextPath: /autodb-backend
  error:
    include-message: always


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 1234
    hikari:
      connection-timeout: 30000
      idleTimeout: 600000
      maxLifeTime: 1800000
  application:
    app: autodb-backend
    name: autodb-backend

  config:
    use-legacy-processing: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: true
        javax:
          persistence:
            validation:
              mode: none


logging:
  level:
    org:

postgresql: true
dbPostgre:
  driver: org.postgresql.Driver
  uri: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 1234
  miPoolSize: 1
  maxPoolsize: 10
  maxStatements: 10
  initialPoolSize: 3
  connectionWaitTimeout: 500

